version: 4.1.1
permalink: /:categories/:year/:month/:day/:title
exclude: ["README.md", "changelog.md"]
relative_permalinks: false
paginate: 5
markdown: kramdown
highlighter: rouge
excerpt_separator: '<!--break-->'
website:
    title: Chris' Blag
    description: Various ramblings.
    image: https://chrislewis.au/images/developer-koala.jpg
    production_url: https://chrislewis.au
author:
    name: Chris Lewis
    email: chris.lewis2@gmail.com
    github: cdlewis
    twitter: chrislewis_aus
    facebook: chris.lewis2
    linkedin: cdlewis
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  blanklines: false
  startings: [html, head, body]
sass:
    sass_dir: ./_includes/css
    style: compressed
plugins:
  - jekyll-paginate
