version: 2
permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
relative_permalinks: false
paginate: 5
title: Chris Lewis
production_url: http://www.chrislewis.com.au
markdown: kramdown
highlighter: pygments
author:
    name: Chris Lewis
    email: chris.lewis2@gmail.com
    github: cdlewis
    twitter: chrislewis_aus
