version: 2
permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
relative_permalinks: false
paginate: 5
markdown: kramdown
highlighter: rouge
excerpt_separator: '<!--break-->'
website:
    title: Chris' Blag
    description: Various ramblings.
    image: http://chrislewis.com.au/assets/images/developer-koala.jpg
    production_url: http://www.chrislewis.com.au
author:
    name: Chris Lewis
    email: chris.lewis2@gmail.com
    github: cdlewis
    twitter: chrislewis_aus
    facebook: chris.lewis2
    linkedin: cdlewis
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  blanklines: false
  startings: [html, head, body]
